<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class RecordsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('records')->insert([
            [
                'staff_id' => 1,
                'typeincident' => 'Fire',
                'datetimeoccurence' => Carbon::now()->subDays(2),
                'barangay' => 'Barangay Uno',
                'specificlocation' => 'Zone 5, Near Market',
                'detaileddesc' => 'A fire broke out in a residential area.',
                'involvedinjured' => 2,
                'involveddead' => 0,
                'filesubmitted' => 'fire_report.pdf',
                'status' => 'Open',
                'process_status' => 'Ongoing',
                'affectedfamilies' => 5,
                'individuals' => 20,
                'evacuationfamilies' => 3,
                'evacuationindividuals' => 12,
                'remarks' => 'Initial response ongoing',
                'clearingoperations' => 'Firefighters deployed',
                'quantity' => null,
                'unit' => null,
                'description' => null,
                'propertyno' => null,
                'dateacquired' => null,
                'amount' => null,
                'typeOfRecord' => 'INCIDENTREPORT',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'staff_id' => 2,
                'typeincident' => 'Flood',
                'datetimeoccurence' => Carbon::now()->subDays(5),
                'barangay' => 'Barangay Dos',
                'specificlocation' => 'Riverside Area',
                'detaileddesc' => 'Flooding due to heavy rains.',
                'involvedinjured' => 0,
                'involveddead' => 0,
                'filesubmitted' => 'flood_report.pdf',
                'status' => 'Closed',
                'process_status' => 'Resolved',
                'affectedfamilies' => 10,
                'individuals' => 45,
                'evacuationfamilies' => 5,
                'evacuationindividuals' => 20,
                'remarks' => 'Relief provided',
                'clearingoperations' => 'Water pumps used',
                'quantity' => null,
                'unit' => null,
                'description' => null,
                'propertyno' => null,
                'dateacquired' => null,
                'amount' => null,
                'typeOfRecord' => 'SITUATIONALREPORT',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'staff_id' => 3,
                'typeincident' => null,
                'datetimeoccurence' => null,
                'barangay' => null,
                'specificlocation' => null,
                'detaileddesc' => 'Warehouse stock count.',
                'involvedinjured' => null,
                'involveddead' => null,
                'filesubmitted' => 'inventory_report.pdf',
                'status' => 'Ongoing',
                'process_status' => 'Checking',
                'affectedfamilies' => null,
                'individuals' => null,
                'evacuationfamilies' => null,
                'evacuationindividuals' => null,
                'remarks' => 'Stock taking in progress',
                'clearingoperations' => null,
                'quantity' => 100,
                'unit' => 'Boxes',
                'description' => 'Relief goods',
                'propertyno' => 'INV-001',
                'dateacquired' => '2024-01-10',
                'amount' => 25000.00,
                'typeOfRecord' => 'INVENTORYREPORT',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'staff_id' => 4,
                'typeincident' => null,
                'datetimeoccurence' => Carbon::now()->subDays(1),
                'barangay' => 'Barangay Tres',
                'specificlocation' => 'Evacuation Center',
                'detaileddesc' => 'Update on ongoing evacuation support.',
                'involvedinjured' => null,
                'involveddead' => null,
                'filesubmitted' => 'progress_report.pdf',
                'status' => 'Ongoing',
                'process_status' => 'In Progress',
                'affectedfamilies' => 7,
                'individuals' => 28,
                'evacuationfamilies' => 7,
                'evacuationindividuals' => 28,
                'remarks' => 'Food distribution continues',
                'clearingoperations' => null,
                'quantity' => null,
                'unit' => null,
                'description' => null,
                'propertyno' => null,
                'dateacquired' => null,
                'amount' => null,
                'typeOfRecord' => 'PROGRESSREPORT',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
//php artisan db:seed --class=RecordsTableSeeder